export default
{
	"noticia": {
		"fields": {
			"id_noticia": {
				"label": "Id noticia",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "id_noticia",
				"value": null,
				"type": "number",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": true,
				"show": false,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": true,
				"max": null,
				"tag": "input",
				"autoIncrement": true,
				"fileLoop": null
			},
			"ds_noticia": {
				"label": "Ds noticia",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "ds_noticia",
				"value": null,
				"type": "search",
				"required": true,
				"invalid": null,
				"unico": true,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": true,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"link_noticia": {
				"label": "Link noticia",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "link_noticia",
				"value": null,
				"type": "search",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": false,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"palavras_chaves_noticia": {
				"label": "Palavras chaves noticia",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "palavras_chaves_noticia",
				"value": null,
				"type": "search",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": false,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"texto_noticia": {
				"label": "Texto noticia",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "texto_noticia",
				"value": null,
				"type": "blog",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "blog",
				"sqlType": "LONGBLOB",
				"notNull": true,
				"max": null,
				"tag": "textarea",
				"autoIncrement": false,
				"fileLoop": null
			},
			"dt_noticia": {
				"label": "Dt noticia",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "dt_noticia",
				"value": null,
				"type": "date",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "date",
				"sqlType": "DATE",
				"notNull": true,
				"max": null,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"ordem_noticia": {
				"label": "Ordem noticia",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "ordem_noticia",
				"value": null,
				"type": "number",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": false,
				"max": null,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			}
		},
		"name": "noticia",
		"label": "Noticia",
		"ds": "ds_noticia",
		"id": [
			"id_noticia"
		],
		"unico": {
			"noticia_index1155": [
				"ds_noticia"
			]
		},
		"fieldLoop": null,
		"permissao": 1
	},
	"produto": {
		"fields": {
			"id_produto": {
				"label": "Id produto",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "id_produto",
				"value": null,
				"type": "number",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": true,
				"show": false,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": true,
				"max": null,
				"tag": "input",
				"autoIncrement": true,
				"fileLoop": null
			},
			"ds_produto": {
				"label": "Ds produto",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "ds_produto",
				"value": null,
				"type": "search",
				"required": true,
				"invalid": null,
				"unico": true,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": true,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"resumo_produto": {
				"label": "Resumo produto",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "resumo_produto",
				"value": null,
				"type": "textarea",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "textarea",
				"sqlType": "VARCHAR(1024)",
				"notNull": false,
				"max": 1024,
				"tag": "textarea",
				"autoIncrement": false,
				"fileLoop": null
			},
			"palavras_chaves_produto": {
				"label": "Palavras chaves produto",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "palavras_chaves_produto",
				"value": null,
				"type": "search",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": false,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"texto_produto": {
				"label": "Texto produto",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "texto_produto",
				"value": null,
				"type": "blog",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "blog",
				"sqlType": "LONGBLOB",
				"notNull": true,
				"max": null,
				"tag": "textarea",
				"autoIncrement": false,
				"fileLoop": null
			},
			"dt_produto": {
				"label": "Dt produto",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "dt_produto",
				"value": null,
				"type": "datetime-local",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "datetime",
				"sqlType": "DATETIME",
				"notNull": false,
				"max": null,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"ordem_produto": {
				"label": "Ordem produto",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "ordem_produto",
				"value": null,
				"type": "number",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": false,
				"max": null,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			}
		},
		"name": "produto",
		"label": "Produto",
		"ds": "ds_produto",
		"id": [
			"id_produto"
		],
		"unico": {
			"produto_index1276": [
				"ds_produto"
			]
		},
		"fieldLoop": null,
		"permissao": 1
	},
	"servico": {
		"fields": {
			"id_servico": {
				"label": "Id servico",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "id_servico",
				"value": null,
				"type": "number",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": true,
				"show": false,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": true,
				"max": null,
				"tag": "input",
				"autoIncrement": true,
				"fileLoop": null
			},
			"ds_servico": {
				"label": "Ds servico",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "ds_servico",
				"value": null,
				"type": "search",
				"required": true,
				"invalid": null,
				"unico": true,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": true,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"resumo_servico": {
				"label": "Resumo servico",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "resumo_servico",
				"value": null,
				"type": "textarea",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "textarea",
				"sqlType": "VARCHAR(1024)",
				"notNull": false,
				"max": 1024,
				"tag": "textarea",
				"autoIncrement": false,
				"fileLoop": null
			},
			"palavras_chaves_servico": {
				"label": "Palavras chaves servico",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "palavras_chaves_servico",
				"value": null,
				"type": "search",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": false,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"texto_servico": {
				"label": "Texto servico",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "texto_servico",
				"value": null,
				"type": "blog",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "blog",
				"sqlType": "LONGBLOB",
				"notNull": true,
				"max": null,
				"tag": "textarea",
				"autoIncrement": false,
				"fileLoop": null
			},
			"ordem_servico": {
				"label": "Ordem servico",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "ordem_servico",
				"value": null,
				"type": "number",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": false,
				"max": null,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			}
		},
		"name": "servico",
		"label": "Servico",
		"ds": "ds_servico",
		"id": [
			"id_servico"
		],
		"unico": {
			"servico_index1042": [
				"ds_servico"
			]
		},
		"fieldLoop": null,
		"permissao": 1
	},
	"sobre": {
		"fields": {
			"id_sobre": {
				"label": "Id sobre",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "id_sobre",
				"value": null,
				"type": "number",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": true,
				"show": false,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": true,
				"max": null,
				"tag": "input",
				"autoIncrement": true,
				"fileLoop": null
			},
			"ds_sobre": {
				"label": "Ds sobre",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "ds_sobre",
				"value": null,
				"type": "search",
				"required": true,
				"invalid": null,
				"unico": true,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": true,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"texto_sobre": {
				"label": "Texto sobre",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "texto_sobre",
				"value": null,
				"type": "blog",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "blog",
				"sqlType": "LONGBLOB",
				"notNull": true,
				"max": null,
				"tag": "textarea",
				"autoIncrement": false,
				"fileLoop": null
			},
			"ativo_sobre": {
				"label": "Ativo sobre",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "ativo_sobre",
				"value": null,
				"type": "checkbox",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "checkbox",
				"sqlType": "BOOLEAN",
				"notNull": true,
				"max": null,
				"tag": "checkbox",
				"autoIncrement": false,
				"fileLoop": null
			}
		},
		"name": "sobre",
		"label": "Sobre",
		"ds": "ds_sobre",
		"id": [
			"id_sobre"
		],
		"unico": {
			"sobre_index1327": [
				"ds_sobre"
			]
		},
		"fieldLoop": null,
		"permissao": 1
	},
	"cliente": {
		"fields": {
			"id_cliente": {
				"label": "Id cliente",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "id_cliente",
				"value": null,
				"type": "number",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": true,
				"show": false,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": true,
				"max": null,
				"tag": "input",
				"autoIncrement": true,
				"fileLoop": null
			},
			"ds_cliente": {
				"label": "Ds cliente",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "ds_cliente",
				"value": null,
				"type": "search",
				"required": true,
				"invalid": null,
				"unico": true,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": true,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"resumo_cliente": {
				"label": "Resumo cliente",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "resumo_cliente",
				"value": null,
				"type": "textarea",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "textarea",
				"sqlType": "VARCHAR(1024)",
				"notNull": false,
				"max": 1024,
				"tag": "textarea",
				"autoIncrement": false,
				"fileLoop": null
			},
			"palavras_chaves_cliente": {
				"label": "Palavras chaves cliente",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "palavras_chaves_cliente",
				"value": null,
				"type": "search",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": false,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"texto_cliente": {
				"label": "Texto cliente",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "texto_cliente",
				"value": null,
				"type": "textarea",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "textarea",
				"sqlType": "VARCHAR(1024)",
				"notNull": true,
				"max": 1024,
				"tag": "textarea",
				"autoIncrement": false,
				"fileLoop": null
			},
			"site_cliente": {
				"label": "Site cliente",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "site_cliente",
				"value": null,
				"type": "search",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": false,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"social_cliente": {
				"label": "Social cliente",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "social_cliente",
				"value": null,
				"type": "textarea",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "textarea",
				"sqlType": "VARCHAR(1024)",
				"notNull": false,
				"max": 1024,
				"tag": "textarea",
				"autoIncrement": false,
				"fileLoop": null
			},
			"dt_cliente": {
				"label": "Dt cliente",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "dt_cliente",
				"value": null,
				"type": "date",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "date",
				"sqlType": "DATE",
				"notNull": true,
				"max": null,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"ordem_clliente": {
				"label": "Ordem clliente",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "ordem_clliente",
				"value": null,
				"type": "number",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": false,
				"max": null,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			}
		},
		"name": "cliente",
		"label": "Cliente",
		"ds": "ds_cliente",
		"id": [
			"id_cliente"
		],
		"unico": {
			"cliente_index1023": [
				"ds_cliente"
			]
		},
		"fieldLoop": null,
		"permissao": 1
	},
	"contato": {
		"fields": {
			"id_contato": {
				"label": "Id contato",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "id_contato",
				"value": null,
				"type": "number",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": true,
				"show": false,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": true,
				"max": null,
				"tag": "input",
				"autoIncrement": true,
				"fileLoop": null
			},
			"ds_contato": {
				"label": "Ds contato",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "ds_contato",
				"value": null,
				"type": "search",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": true,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"dt_contato": {
				"label": "Dt contato",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "dt_contato",
				"value": null,
				"type": "datetime-local",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "datetime",
				"sqlType": "DATETIME",
				"notNull": true,
				"max": null,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"email_contato": {
				"label": "Email contato",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "email_contato",
				"value": null,
				"type": "search",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": false,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"telefone_contato": {
				"label": "Telefone contato",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "telefone_contato",
				"value": null,
				"type": "search",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": false,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"obs_contato": {
				"label": "Obs contato",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "obs_contato",
				"value": null,
				"type": "textarea",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "textarea",
				"sqlType": "VARCHAR(1024)",
				"notNull": true,
				"max": 1024,
				"tag": "textarea",
				"autoIncrement": false,
				"fileLoop": null
			},
			"ip_contato": {
				"label": "Ip contato",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "ip_contato",
				"value": null,
				"type": "search",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": false,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"porta_contato": {
				"label": "Porta contato",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "porta_contato",
				"value": null,
				"type": "number",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": false,
				"max": null,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"local_contato": {
				"label": "Local contato",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "local_contato",
				"value": null,
				"type": "textarea",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "textarea",
				"sqlType": "VARCHAR(1024)",
				"notNull": false,
				"max": 1024,
				"tag": "textarea",
				"autoIncrement": false,
				"fileLoop": null
			}
		},
		"name": "contato",
		"label": "Contato",
		"ds": "ds_contato",
		"id": [
			"id_contato"
		],
		"unico": {},
		"fieldLoop": null,
		"permissao": 1
	},
	"cliente_x_servico": {
		"fields": {
			"cliente_id_cliente": {
				"label": "Cliente id cliente",
				"foreignKeyTable": "cliente",
				"foreignKeyFieldDs": "ds_cliente",
				"foreignKeyId": "id_cliente",
				"foreignKey": true,
				"name": "cliente_id_cliente",
				"value": null,
				"type": "number",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": true,
				"show": true,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": true,
				"max": null,
				"tag": "select",
				"autoIncrement": false,
				"fileLoop": null
			},
			"servico_id_servico": {
				"label": "Servico id servico",
				"foreignKeyTable": "servico",
				"foreignKeyFieldDs": "ds_servico",
				"foreignKeyId": "id_servico",
				"foreignKey": true,
				"name": "servico_id_servico",
				"value": null,
				"type": "number",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": true,
				"show": true,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": true,
				"max": null,
				"tag": "select",
				"autoIncrement": false,
				"fileLoop": null
			},
			"dt_cliente_x_servico": {
				"label": "Dt cliente x servico",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "dt_cliente_x_servico",
				"value": null,
				"type": "date",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "date",
				"sqlType": "DATE",
				"notNull": true,
				"max": null,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			}
		},
		"name": "cliente_x_servico",
		"label": "Cliente_x_servico",
		"ds": "dt_cliente_x_servico",
		"id": [
			"cliente_id_cliente",
			"servico_id_servico"
		],
		"unico": {},
		"fieldLoop": null,
		"permissao": 1
	},
	"foto": {
		"fields": {
			"id_foto": {
				"label": "Id foto",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "id_foto",
				"value": null,
				"type": "number",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": true,
				"show": false,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": true,
				"max": null,
				"tag": "input",
				"autoIncrement": true,
				"fileLoop": null
			},
			"id_sobre": {
				"label": "Id sobre",
				"foreignKeyTable": "sobre",
				"foreignKeyFieldDs": "ds_sobre",
				"foreignKeyId": "id_sobre",
				"foreignKey": true,
				"name": "id_sobre",
				"value": null,
				"type": "number",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": false,
				"max": null,
				"tag": "select",
				"autoIncrement": false,
				"fileLoop": null
			},
			"id_produto": {
				"label": "Id produto",
				"foreignKeyTable": "produto",
				"foreignKeyFieldDs": "ds_produto",
				"foreignKeyId": "id_produto",
				"foreignKey": true,
				"name": "id_produto",
				"value": null,
				"type": "number",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": false,
				"max": null,
				"tag": "select",
				"autoIncrement": false,
				"fileLoop": null
			},
			"id_noticia": {
				"label": "Id noticia",
				"foreignKeyTable": "noticia",
				"foreignKeyFieldDs": "ds_noticia",
				"foreignKeyId": "id_noticia",
				"foreignKey": true,
				"name": "id_noticia",
				"value": null,
				"type": "number",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": false,
				"max": null,
				"tag": "select",
				"autoIncrement": false,
				"fileLoop": null
			},
			"id_cliente": {
				"label": "Id cliente",
				"foreignKeyTable": "cliente",
				"foreignKeyFieldDs": "ds_cliente",
				"foreignKeyId": "id_cliente",
				"foreignKey": true,
				"name": "id_cliente",
				"value": null,
				"type": "number",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": false,
				"max": null,
				"tag": "select",
				"autoIncrement": false,
				"fileLoop": null
			},
			"id_servico": {
				"label": "Id servico",
				"foreignKeyTable": "servico",
				"foreignKeyFieldDs": "ds_servico",
				"foreignKeyId": "id_servico",
				"foreignKey": true,
				"name": "id_servico",
				"value": null,
				"type": "number",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": false,
				"max": null,
				"tag": "select",
				"autoIncrement": false,
				"fileLoop": null
			},
			"ds_foto": {
				"label": "Ds foto",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "ds_foto",
				"value": null,
				"type": "search",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": false,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"img_foto": {
				"label": "Img foto",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "img_foto",
				"value": null,
				"type": "file",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "img",
				"sqlType": "CHAR(100)",
				"notNull": true,
				"max": 100,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"dt_foto": {
				"label": "Dt foto",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "dt_foto",
				"value": null,
				"type": "date",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "date",
				"sqlType": "DATE",
				"notNull": true,
				"max": null,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"home": {
				"label": "Home",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "home",
				"value": null,
				"type": "checkbox",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "checkbox",
				"sqlType": "BOOLEAN",
				"notNull": true,
				"max": null,
				"tag": "checkbox",
				"autoIncrement": false,
				"fileLoop": null
			},
			"sobre": {
				"label": "Sobre",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "sobre",
				"value": null,
				"type": "checkbox",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "checkbox",
				"sqlType": "BOOLEAN",
				"notNull": true,
				"max": null,
				"tag": "checkbox",
				"autoIncrement": false,
				"fileLoop": null
			},
			"capa": {
				"label": "Capa",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "capa",
				"value": null,
				"type": "checkbox",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "checkbox",
				"sqlType": "BOOLEAN",
				"notNull": true,
				"max": null,
				"tag": "checkbox",
				"autoIncrement": false,
				"fileLoop": null
			},
			"ordem_foto": {
				"label": "Ordem foto",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "ordem_foto",
				"value": null,
				"type": "number",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": false,
				"max": null,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			}
		},
		"name": "foto",
		"label": "Foto",
		"ds": "ds_foto",
		"id": [
			"id_foto"
		],
		"unico": {},
		"fieldLoop": "img_foto",
		"permissao": 1
	},
	"usuario": {
		"fields": {
			"id_usuario": {
				"label": "Id usuario",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "id_usuario",
				"value": null,
				"type": "number",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": true,
				"show": false,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": true,
				"max": null,
				"tag": "input",
				"autoIncrement": true,
				"fileLoop": null
			},
			"email_usuario": {
				"label": "Email usuario",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "email_usuario",
				"value": null,
				"type": "search",
				"required": true,
				"invalid": null,
				"unico": true,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": true,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"senha_usuario": {
				"label": "Senha usuario",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "senha_usuario",
				"value": null,
				"type": "password",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "password",
				"sqlType": "VARCHAR(32)",
				"notNull": true,
				"max": 32,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"nivel_usuario": {
				"label": "Nivel usuario",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "nivel_usuario",
				"value": null,
				"type": "number",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "int",
				"sqlType": "TINYINT",
				"notNull": true,
				"max": null,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"telegram_usuario": {
				"label": "Telegram usuario",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "telegram_usuario",
				"value": null,
				"type": "search",
				"required": false,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": false,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"tentativas_usuario": {
				"label": "Tentativas usuario",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "tentativas_usuario",
				"value": null,
				"type": "number",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": true,
				"max": null,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"dt_usuario": {
				"label": "Dt usuario",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "dt_usuario",
				"value": null,
				"type": "date",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "date",
				"sqlType": "DATE",
				"notNull": true,
				"max": null,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			}
		},
		"name": "usuario",
		"label": "Usuario",
		"ds": "email_usuario",
		"id": [
			"id_usuario"
		],
		"unico": {
			"usuario_index1006": [
				"email_usuario"
			]
		},
		"fieldLoop": null,
		"permissao": 2
	},
	"logg": {
		"fields": {
			"id_logg": {
				"label": "Id logg",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "id_logg",
				"value": null,
				"type": "number",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": true,
				"show": false,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": true,
				"max": null,
				"tag": "input",
				"autoIncrement": true,
				"fileLoop": null
			},
			"id_usuario": {
				"label": "Id usuario",
				"foreignKeyTable": "usuario",
				"foreignKeyFieldDs": "email_usuario",
				"foreignKeyId": "id_usuario",
				"foreignKey": true,
				"name": "id_usuario",
				"value": null,
				"type": "number",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "int",
				"sqlType": "INT",
				"notNull": true,
				"max": null,
				"tag": "select",
				"autoIncrement": false,
				"fileLoop": null
			},
			"ip_logg": {
				"label": "Ip logg",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "ip_logg",
				"value": null,
				"type": "search",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "text",
				"sqlType": "VARCHAR(255)",
				"notNull": true,
				"max": 255,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			},
			"dt_logg": {
				"label": "Dt logg",
				"foreignKeyTable": null,
				"foreignKeyFieldDs": null,
				"foreignKeyId": null,
				"foreignKey": null,
				"name": "dt_logg",
				"value": null,
				"type": "datetime-local",
				"required": true,
				"invalid": null,
				"unico": null,
				"primaryKey": null,
				"show": true,
				"ktype": "datetime",
				"sqlType": "DATETIME",
				"notNull": true,
				"max": null,
				"tag": "input",
				"autoIncrement": false,
				"fileLoop": null
			}
		},
		"name": "logg",
		"label": "Logg",
		"ds": "id_usuario",
		"id": [
			"id_logg"
		],
		"unico": {},
		"fieldLoop": null,
		"permissao": 2
	}
}